######################################################################################################
##### 通用配置 start #####
management:
  endpoints:
    web:
      exposure:
        #include: loggers #暴露日志endpoints，可动态调整日志级别，请求类似：curl 'http://localhost:8080/actuator/loggers/com.broadtech.web' -X POST -H 'Content-Type: application/json' -d '{"configuredLevel":"debug"}'
        include: '*'  # 开启所有
#        exclude: '*'  # 关闭所有
  
spring:
  profiles:
    active: dev


  output: # 彩色控制台日志
    ansi:
      enabled: always

  main:
    allow-bean-definition-overriding: true

  servlet: # 文件上传大小控制
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true

#  security:
#    user:
#      name: monitor
#      password: ${MR_PD:monito!r}


logging:
  file:
    name: logs/${spring.application.name:app}.log

ribbon: # 超时
  ReadTimeout: 3600000
  ConnectTimeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

minio:
  url: https://play.min.io # minio服务地址，缺省值 http://localhost:9000
  bucketName: s-jqs # 桶名，缺省值 public
  accessKey: Q3AM3UQ867SPQQA43P2F # 公钥，缺省值 minioadmin
  secretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG # 私钥，缺省值 minioadmin

#项目信息
info:
  #自定义显示信息
  '[名称]': ${spring.application.name}
  '[版本]': @project.version@

##### 通用配置 end #####
######################################################################################################
##### dev 环境个性化配置 start #####
---
spring:
  profiles: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${DB_ADDR:xxx:3306/microservice-framework}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: ${DB_USER:root}
#    password: ${DB_PD:root}


##### dev 环境个性化配置 end #####
######################################################################################################
##### test 环境个性化配置 start #####
---
spring:
  profiles: test

##### test 环境个性化配置 end #####
######################################################################################################
##### prod 环境个性化配置 start #####
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ADDR:localhost:3306/microservice-framework}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${DB_USER:root}
    password: ${DB_PD:roo!!!!t}


##### prod 环境个性化配置 end #####
######################################################################################################

