server:
  port: 30015
spring:
  application:
    name: kg-server

  profiles:
    include: base
    active: dev
#项目信息
info:
  #自定义显示信息
  '[描述]': 知识图谱查询服务



### nebula graph client ###
myapp:
  nebula:
    hosts: 10.36.253.10:9669
    username: root
    password: nebula
    max-conn: 10



nebula:
  ngbatis:
    # ^v1.1.2
    # 连接使用 nebula-java 中的 SessionPool
    use-session-pool: true
  # 填入 graphd 的 ip 和端口号，下面仅供参考
  hosts: 10.36.253.10:9669
  # 连接图数据库所用的用户名
  username: root
  # 连接图数据库所用的密码
  password: nebula
  # 所要连接的图数据库图空间名
  space: demo_basketballplayer
  # 连接池配置
  pool-config:
    # 连接池中最小空闲连接数
    min-conns-size: 0
    # 连接池中最大空闲连接数
    max-conns-size: 10
    # 客户端同服务端建立连接的超时时间设置，单位为 ms；超过设定时间未建立起连接，则报错
    timeout: 0
    # 连接空闲时间，为 0 表示连接永不删除，单位为 ms
    idle-time: 0
    # 连接池检测空闲连接的时间间隔，为 -1 表示不进行检测
    interval-idle: -1
    # 连接等候时间，超过则不再等候连接
    wait-time: 0
    # 集群允许最小的服务可用率，1.0 表示为所有机器 graphd 可用，0.25 表示集群中 1/4 机器可用即可
    min-cluster-health-rate: 1.0
    # 是否允许 SSL 连接，目前暂不支持
    enable-ssl: false